# Generated by Django 4.2.10 on 2024-07-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscountCondition",
            fields=[
                (
                    "bank",
                    models.CharField(max_length=25, verbose_name="Commerical Bank"),
                ),
                (
                    "discount_name",
                    models.CharField(
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Interest rate discount name",
                    ),
                ),
                (
                    "money_transfer_condition",
                    models.IntegerField(blank=True, null=True),
                ),
                ("payment_condition", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Interest rate discount condition",
                "verbose_name_plural": "Interest rate discount conditions",
                "db_table": "discount_condition",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DiscountValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount_rate_id", models.CharField(max_length=250, unique=True)),
                ("loan_type", models.CharField(max_length=25)),
                ("term_trh_low", models.IntegerField()),
                ("term_trh_upper", models.IntegerField()),
                ("discount_rate", models.FloatField()),
            ],
            options={"db_table": "discount_value", "managed": False,},
        ),
        migrations.CreateModel(
            name="IncomeTrh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("income_rule_id", models.IntegerField()),
                ("interest_period_min", models.IntegerField(blank=True, null=True)),
                ("interest_period_max", models.FloatField(blank=True, null=True)),
                ("income_min", models.IntegerField(blank=True, null=True)),
                ("income_max", models.FloatField(blank=True, null=True)),
                ("upper_limit", models.FloatField()),
            ],
            options={"db_table": "income_trh", "managed": False,},
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "insurance_rate_id",
                    models.CharField(
                        max_length=250, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "bank",
                    models.CharField(max_length=25, verbose_name="Commerical Bank"),
                ),
                ("loan_type", models.CharField(max_length=25)),
                ("insurance_coverage_type", models.CharField(max_length=25)),
                ("insurance_rate", models.FloatField()),
            ],
            options={"db_table": "insurance", "managed": False,},
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("loan_type", models.CharField(max_length=25)),
                (
                    "bank",
                    models.CharField(max_length=25, verbose_name="Commerical Bank"),
                ),
                (
                    "loan_name",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("term_min", models.IntegerField()),
                ("term_max", models.IntegerField()),
                ("interest_rate", models.FloatField()),
                ("interest_period", models.IntegerField()),
                ("total_loan_fee_ind", models.FloatField()),
                ("discount_eligible", models.CharField(max_length=3)),
                ("insurance_possible", models.CharField(max_length=3)),
            ],
            options={"db_table": "loan", "managed": False,},
        ),
    ]
