# Generated by Django 4.2.10 on 2024-07-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_commonbankfield_commonloantype"),
    ]

    operations = [
        migrations.DeleteModel(name="CommonBankField",),
        migrations.DeleteModel(name="CommonLoanType",),
    ]
